// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_mvc_aspnet_core.Data;

namespace crud_mvc_aspnet_core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crud_mvc_aspnet_core.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(1481),
                            Description = "Adidas, poliester",
                            Name = "camisa deportiva",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3749),
                            Description = "Adidas, poliester 95%",
                            Name = "pantalon deportivo",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3834),
                            Description = "Calvin Klein",
                            Name = "calzones boxer",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3836),
                            Description = "Kevingston",
                            Name = "calzones boxer",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3838),
                            Description = "Nike",
                            Name = "jean",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3840),
                            Description = "Gucci",
                            Name = "jean",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3842),
                            Description = "Bosch",
                            Name = "martillo neumatico",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3843),
                            Description = "Makita, año 2010",
                            Name = "desmalezadora",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3845),
                            Description = "Stanley, año 2015",
                            Name = "amoladora",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3847),
                            Description = "Hyundai",
                            Name = "desmalezadora",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3848),
                            Description = "Gaffa",
                            Name = "heladera",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3850),
                            Description = "Electroluz",
                            Name = "lavarropas",
                            Quantity = 40
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3852),
                            Description = "General Electric",
                            Name = "cocina",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3853),
                            Description = "LG, año 2012",
                            Name = "heladera",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3855),
                            Description = "LG, reacondicionadas/nuevas",
                            Name = "heladera",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3857),
                            Description = "Sanyo, año 2005",
                            Name = "lavavajillas",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3859),
                            Description = "Microsoft, nuevas",
                            Name = "consola xbox",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3860),
                            Description = "modelo Genesis 3, a reparar/nuevas",
                            Name = "sega",
                            Quantity = 80
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3862),
                            Description = "original, a reparar/nuevas",
                            Name = "consola playstation 2",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3864),
                            Description = "generico",
                            Name = "lapiz 3D impresora",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 11, 4, 16, 59, 42, 823, DateTimeKind.Utc).AddTicks(3867),
                            Description = "Hasbro, año 2000",
                            Name = "monopoli",
                            Quantity = 30
                        });
                });

            modelBuilder.Entity("crud_mvc_aspnet_core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 11, 4, 13, 59, 42, 820, DateTimeKind.Local).AddTicks(1746),
                            Name = "Indumentaria"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 11, 4, 13, 59, 42, 821, DateTimeKind.Local).AddTicks(7930),
                            Name = "Herramientas"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 11, 4, 13, 59, 42, 821, DateTimeKind.Local).AddTicks(7991),
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 11, 4, 13, 59, 42, 821, DateTimeKind.Local).AddTicks(7994),
                            Name = "Ocio"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 11, 4, 13, 59, 42, 821, DateTimeKind.Local).AddTicks(7996),
                            Name = "Otro"
                        });
                });

            modelBuilder.Entity("crud_mvc_aspnet_core.Models.Article", b =>
                {
                    b.HasOne("crud_mvc_aspnet_core.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
